In [21]:
import pandas as pd
import numpy as np

In [22]:
immo = pd.read_csv('../../data/join/immo_by_month_100.csv',sep=',',dtype= {'code_commune' : str}).rename(columns = {'id_bien_int':'id_bien'})

In [23]:
immo.shape

(228000, 4)

In [24]:
immo.head(13)

    id_bien  month  year         valeur
0        16      1  2014  244117.392000
1        16      2  2014  256866.666667
2        16      3  2014  193337.500000
3        16      4  2014  181700.000000
4        16      5  2014  184250.000000
5        16      6  2014  236000.000000
6        16      7  2014  202333.333333
7        16      8  2014  208412.500000
8        16      9  2014  210381.000000
9        16     10  2014  228424.000000
10       16     11  2014  264625.000000
11       16     12  2014  209200.000000
12       16      1  2015  209500.000000

### Feature enginneering sur les timesetps ( month + year )

In [25]:
immo['mnth_sin'] = np.sin((immo.month-1)*(2.*np.pi/12))
immo['mnth_cos'] = np.cos((immo.month-1)*(2.*np.pi/12))

In [30]:
immo['mois'] = immo['month'] + (immo['year']-2014)*12

In [31]:
immo.head(12)

    id_bien  month  year         valeur      mnth_sin      mnth_cos  mois
0        16      1  2014  244117.392000  0.000000e+00  1.000000e+00     1
1        16      2  2014  256866.666667  5.000000e-01  8.660254e-01     2
2        16      3  2014  193337.500000  8.660254e-01  5.000000e-01     3
3        16      4  2014  181700.000000  1.000000e+00  6.123234e-17     4
4        16      5  2014  184250.000000  8.660254e-01 -5.000000e-01     5
5        16      6  2014  236000.000000  5.000000e-01 -8.660254e-01     6
6        16      7  2014  202333.333333  1.224647e-16 -1.000000e+00     7
7        16      8  2014  208412.500000 -5.000000e-01 -8.660254e-01     8
8        16      9  2014  210381.000000 -8.660254e-01 -5.000000e-01     9
9        16     10  2014  228424.000000 -1.000000e+00 -1.836970e-16    10
10       16     11  2014  264625.000000 -8.660254e-01  5.000000e-01    11
11       16     12  2014  209200.000000 -5.000000e-01  8.660254e-01    12

In [36]:
immo2 = immo.copy()

### Feature enginneering - ajout des variables observées à  t-i  ( lagk) avec i  dans [[1;k]]

In [37]:
cols_to_extract = ['valeur']

In [38]:
k = 12

In [39]:
for i in range(1,k+1):
    lag1 = list(map(lambda x: x + "-"+str(i),cols_to_extract))
    immo2[lag1] = immo2.groupby(['id_bien'])[cols_to_extract].shift(i)

In [40]:
immo2.sort_values(by=['id_bien','mois']).head(20)

,id_bien,month,year,valeur,mnth_sin,mnth_cos,mois,valeur-1,valeur-2,valeur-3,valeur-4,valeur-5,valeur-6,valeur-7,valeur-8,valeur-9,valeur-10,valeur-11,valeur-12
0,16,1,2014,244117.392000,0.000000e+00,1.000000e+00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,2,2014,256866.666667,5.000000e-01,8.660254e-01,2,244117.392000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16,3,2014,193337.500000,8.660254e-01,5.000000e-01,3,256866.666667,244117.392000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16,4,2014,181700.000000,1.000000e+00,6.123234e-17,4,193337.500000,256866.666667,244117.392000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,5,2014,184250.000000,8.660254e-01,-5.000000e-01,5,181700.000000,193337.500000,256866.666667,244117.392000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,16,6,2014,236000.000000,5.000000e-01,-8.660254e-01,6,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16,7,2014,202333.333333,1.224647e-16,-1.000000e+00,7,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000,NaN,NaN,NaN,NaN,NaN,NaN
7,16,8,2014,208412.500000,-5.000000e-01,-8.660254e-01,8,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000,NaN,NaN,NaN,NaN,NaN
8,16,9,2014,210381.000000,-8.660254e-01,-5.000000e-01,9,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000,NaN,NaN,NaN,NaN
9,16,10,2014,228424.000000,-1.000000e+00,-1.836970e-16,10,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000,NaN,NaN,NaN
10,16,11,2014,264625.000000,-8.660254e-01,5.000000e-01,11,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000,NaN,NaN
11,16,12,2014,209200.000000,-5.000000e-01,8.660254e-01,12,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000,NaN
12,16,1,2015,209500.000000,0.000000e+00,1.000000e+00,13,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667,244117.392000
13,16,2,2015,174100.000000,5.000000e-01,8.660254e-01,14,209500.000000,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000,256866.666667
14,16,3,2015,276600.000000,8.660254e-01,5.000000e-01,15,174100.000000,209500.000000,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000,193337.500000
15,16,4,2015,248566.666667,1.000000e+00,6.123234e-17,16,276600.000000,174100.000000,209500.000000,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000,181700.000000
16,16,5,2015,229313.333333,8.660254e-01,-5.000000e-01,17,248566.666667,276600.000000,174100.000000,209500.000000,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000,184250.000000
17,16,6,2015,148330.000000,5.000000e-01,-8.660254e-01,18,229313.333333,248566.666667,276600.000000,174100.000000,209500.000000,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333,236000.000000
18,16,7,2015,194712.500000,1.224647e-16,-1.000000e+00,19,148330.000000,229313.333333,248566.666667,276600.000000,174100.000000,209500.000000,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000,202333.333333
19,16,8,2015,0.000000,-5.000000e-01,-8.660254e-01,20,194712.500000,148330.000000,229313.333333,248566.666667,276600.000000,174100.000000,209500.000000,209200.000000,264625.000000,228424.000000,210381.000000,208412.500000

### Feature enginneering - ajout des différences entre t-i et t-(i+1) (diffi) pour i dans [[1;k]]

In [41]:
k=10
for i in range(1,k+1):
    lag1 = list(map(lambda x: x + "-"+str(i),cols_to_extract))
    diff1 = list(map(lambda x: x + "_diff-"+str(i)+"-"+str(i+1),cols_to_extract))
    immo2[diff1] = immo2.groupby(['id_bien'])[lag1].diff()

In [42]:
immo2.sort_values(by=['id_bien','mois']).head(20)

,id_bien,month,year,valeur,mnth_sin,mnth_cos,mois,valeur-1,valeur-2,valeur-3,...,valeur_diff-1-2,valeur_diff-2-3,valeur_diff-3-4,valeur_diff-4-5,valeur_diff-5-6,valeur_diff-6-7,valeur_diff-7-8,valeur_diff-8-9,valeur_diff-9-10,valeur_diff-10-11
0,16,1,2014,244117.392000,0.000000e+00,1.000000e+00,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,2,2014,256866.666667,5.000000e-01,8.660254e-01,2,244117.392000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16,3,2014,193337.500000,8.660254e-01,5.000000e-01,3,256866.666667,244117.392000,NaN,...,12749.274667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16,4,2014,181700.000000,1.000000e+00,6.123234e-17,4,193337.500000,256866.666667,244117.392000,...,-63529.166667,12749.274667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,5,2014,184250.000000,8.660254e-01,-5.000000e-01,5,181700.000000,193337.500000,256866.666667,...,-11637.500000,-63529.166667,12749.274667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,16,6,2014,236000.000000,5.000000e-01,-8.660254e-01,6,184250.000000,181700.000000,193337.500000,...,2550.000000,-11637.500000,-63529.166667,12749.274667,NaN,NaN,NaN,NaN,NaN,NaN
6,16,7,2014,202333.333333,1.224647e-16,-1.000000e+00,7,236000.000000,184250.000000,181700.000000,...,51750.000000,2550.000000,-11637.500000,-63529.166667,12749.274667,NaN,NaN,NaN,NaN,NaN
7,16,8,2014,208412.500000,-5.000000e-01,-8.660254e-01,8,202333.333333,236000.000000,184250.000000,...,-33666.666667,51750.000000,2550.000000,-11637.500000,-63529.166667,12749.274667,NaN,NaN,NaN,NaN
8,16,9,2014,210381.000000,-8.660254e-01,-5.000000e-01,9,208412.500000,202333.333333,236000.000000,...,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000,-63529.166667,12749.274667,NaN,NaN,NaN
9,16,10,2014,228424.000000,-1.000000e+00,-1.836970e-16,10,210381.000000,208412.500000,202333.333333,...,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000,-63529.166667,12749.274667,NaN,NaN
10,16,11,2014,264625.000000,-8.660254e-01,5.000000e-01,11,228424.000000,210381.000000,208412.500000,...,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000,-63529.166667,12749.274667,NaN
11,16,12,2014,209200.000000,-5.000000e-01,8.660254e-01,12,264625.000000,228424.000000,210381.000000,...,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000,-63529.166667,12749.274667
12,16,1,2015,209500.000000,0.000000e+00,1.000000e+00,13,209200.000000,264625.000000,228424.000000,...,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000,-63529.166667
13,16,2,2015,174100.000000,5.000000e-01,8.660254e-01,14,209500.000000,209200.000000,264625.000000,...,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000
14,16,3,2015,276600.000000,8.660254e-01,5.000000e-01,15,174100.000000,209500.000000,209200.000000,...,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000
15,16,4,2015,248566.666667,1.000000e+00,6.123234e-17,16,276600.000000,174100.000000,209500.000000,...,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000
16,16,5,2015,229313.333333,8.660254e-01,-5.000000e-01,17,248566.666667,276600.000000,174100.000000,...,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667
17,16,6,2015,148330.000000,5.000000e-01,-8.660254e-01,18,229313.333333,248566.666667,276600.000000,...,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667
18,16,7,2015,194712.500000,1.224647e-16,-1.000000e+00,19,148330.000000,229313.333333,248566.666667,...,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000
19,16,8,2015,0.000000,-5.000000e-01,-8.660254e-01,20,194712.500000,148330.000000,229313.333333,...,46382.500000,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000

In [43]:
immo2.shape

(228000, 29)

In [44]:
immo_train = immo2.dropna()

In [45]:
immo_train.shape

(171000, 29)

### Export

In [46]:
immo_train.to_csv('../../data/ml/train_immo_100_more_k_12_10.csv',index=False)

In [47]:
immo_train.sort_values(by=['id_bien','mois']).head(50)

,id_bien,month,year,valeur,mnth_sin,mnth_cos,mois,valeur-1,valeur-2,valeur-3,...,valeur_diff-1-2,valeur_diff-2-3,valeur_diff-3-4,valeur_diff-4-5,valeur_diff-5-6,valeur_diff-6-7,valeur_diff-7-8,valeur_diff-8-9,valeur_diff-9-10,valeur_diff-10-11
12,16,1,2015,209500.000000,0.000000e+00,1.000000e+00,13,209200.000000,264625.000000,228424.000000,...,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000,-63529.166667
13,16,2,2015,174100.000000,5.000000e-01,8.660254e-01,14,209500.000000,209200.000000,264625.000000,...,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000,-11637.500000
14,16,3,2015,276600.000000,8.660254e-01,5.000000e-01,15,174100.000000,209500.000000,209200.000000,...,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000,2550.000000
15,16,4,2015,248566.666667,1.000000e+00,6.123234e-17,16,276600.000000,174100.000000,209500.000000,...,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667,51750.000000
16,16,5,2015,229313.333333,8.660254e-01,-5.000000e-01,17,248566.666667,276600.000000,174100.000000,...,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667,-33666.666667
17,16,6,2015,148330.000000,5.000000e-01,-8.660254e-01,18,229313.333333,248566.666667,276600.000000,...,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000,6079.166667
18,16,7,2015,194712.500000,1.224647e-16,-1.000000e+00,19,148330.000000,229313.333333,248566.666667,...,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000,1968.500000
19,16,8,2015,0.000000,-5.000000e-01,-8.660254e-01,20,194712.500000,148330.000000,229313.333333,...,46382.500000,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000,18043.000000
20,16,9,2015,225850.000000,-8.660254e-01,-5.000000e-01,21,0.000000,194712.500000,148330.000000,...,-194712.500000,46382.500000,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000,36201.000000
21,16,10,2015,215570.000000,-1.000000e+00,-1.836970e-16,22,225850.000000,0.000000,194712.500000,...,225850.000000,-194712.500000,46382.500000,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000,-55425.000000
22,16,11,2015,197450.000000,-8.660254e-01,5.000000e-01,23,215570.000000,225850.000000,0.000000,...,-10280.000000,225850.000000,-194712.500000,46382.500000,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000,300.000000
23,16,12,2015,234425.000000,-5.000000e-01,8.660254e-01,24,197450.000000,215570.000000,225850.000000,...,-18120.000000,-10280.000000,225850.000000,-194712.500000,46382.500000,-80983.333333,-19253.333333,-28033.333333,102500.000000,-35400.000000
24,16,1,2016,198350.000000,0.000000e+00,1.000000e+00,25,234425.000000,197450.000000,215570.000000,...,36975.000000,-18120.000000,-10280.000000,225850.000000,-194712.500000,46382.500000,-80983.333333,-19253.333333,-28033.333333,102500.000000
25,16,2,2016,216058.333333,5.000000e-01,8.660254e-01,26,198350.000000,234425.000000,197450.000000,...,-36075.000000,36975.000000,-18120.000000,-10280.000000,225850.000000,-194712.500000,46382.500000,-80983.333333,-19253.333333,-28033.333333
26,16,3,2016,218000.000000,8.660254e-01,5.000000e-01,27,216058.333333,198350.000000,234425.000000,...,17708.333333,-36075.000000,36975.000000,-18120.000000,-10280.000000,225850.000000,-194712.500000,46382.500000,-80983.333333,-19253.333333
27,16,4,2016,197625.000000,1.000000e+00,6.123234e-17,28,218000.000000,216058.333333,198350.000000,...,1941.666667,17708.333333,-36075.000000,36975.000000,-18120.000000,-10280.000000,225850.000000,-194712.500000,46382.500000,-80983.333333
28,16,5,2016,154892.600000,8.660254e-01,-5.000000e-01,29,197625.000000,218000.000000,216058.333333,...,-20375.000000,1941.666667,17708.333333,-36075.000000,36975.000000,-18120.000000,-10280.000000,225850.000000,-194712.500000,46382.500000
29,16,6,2016,189315.000000,5.000000e-01,-8.660254e-01,30,154892.600000,197625.000000,218000.000000,...,-42732.400000,-20375.000000,1941.666667,17708.333333,-36075.000000,36975.000000,-18120.000000,-10280.000000,225850.000000,-194712.500000
30,16,7,2016,273000.000000,1.224647e-16,-1.000000e+00,31,189315.000000,154892.600000,197625.000000,...,34422.400000,-42732.400000,-20375.000000,1941.666667,17708.333333,-36075.000000,36975.000000,-18120.000000,-10280.000000,225850.000000
31,16,8,2016,270100.000000,-5.000000e-01,-8.660254e-01,32,273000.000000,189315.000000,154892.600000,...,83685.000000,34422.400000,-42732.400000,-20375.000000,1941.666667,17708.333333,-36075.000000,36975.000000,-18120.000000,-10280.000000
32,16,9,2016,168666.666667,-8.660254e-01,-5.000000e-01,33,270100.000000,273000.000000,189315.000000,...,-2900.000000,83685.000000,34422.400000,-42732.400000,-20375.000000,1941.666667,17708.333333,-36075.000000,36975.000000,-18120.000000
33,16,10,2016,394725.500000,-1.000000e+00,-1.836970e-16,34,168666.666667,270100.000000,273000.000000,...,-101433.333333,-2900.000000,83685.000000,34422.400000,-42732.400000,-20375.000000,1941.666667,17708.333333,-36075.000000,36975.000000
34,16,11,2016,207683.333333,-8.660254e-01,5.000000e-01,35,394725.500000,168666.666667,270100.000000,...,226058.833333,-101433.333333,-2900.000000,83685.000000,34422.400000,-42732.400000,-20375.000000,1941.666667,17708.333333,-36075.000000
35,16,12,2016,218300.000000,-5.000000e-01,8.660254e-01,36,207683.333333,394725.500000,168666.666667,...,-187042.166667,226058.833333,-101433.333333,-2900.000000,83685.000000,34422.400000,-42732.400000,-20375.000000,1941.666667,17708.333333
36,16,1,2017,159025.000000,0.000000e+00,1.000000e+00,37,218300.000000,207683.333333,394725.500000,...,10616.666667,-187042.166667,226058.833333,-101433.333333,-2900.000000,83685.000000,34422.400000,-42732.400000,-20375.000000,1941.666667
37,16,2,2017,165140.600000,5.000000e-01,8.660254e-01,38,159025.000000,218300.000000,207683.333333,...,-59275.000000,10616.666667,-187042.166667,226058.833333,-101433.333333,-2900.000000,83685.000000,34422.400000,-42732.400000,-20375.000000
38,16,3,2017,231915.333333,8.660254e-01,5.000000e-01,39,165140.600000,159025.000000,218300.000000,...,6115.600000,-59275.000000,10616.666667,-187042.166667,226058.833333,-101433.333333,-2900.000000,83685.000000,34422.400000,-42732.400000
39,16,4,2017,186483.333333,1.000000e+00,6.123234e-17,40,231915.333333,165140.600000,159025.000000,...,66774.733333,6115.600000,-59275.000000,10616.666667,-187042.166667,226058.833333,-101433.333333,-2900.000000,83685.000000,34422.400000
40,16,5,2017,218375.000000,8.660254e-01,-5.000000e-01,41,186483.333333,231915.333333,165140.600000,...,-45432.000000,66774.733333,6115.600000,-59275.000000,10616.666667,-187042.166667,226058.833333,-101433.333333,-2900.000000,83685.000000
41,16,6,2017,177540.000000,5.000000e-01,-8.660254e-01,42,218375.000000,186483.333333,231915.333333,...,31891.666667,-45432.000000,66774.733333,6115.600000,-59275.000000,10616.666667,-187042.166667,226058.833333,-101433.333333,-2900.000000
42,16,7,2017,176720.000000,1.224647e-16,-1.000000e+00,43,177540.000000,218375.000000,186483.333333,...,-40835.000000,31891.666667,-45432.000000,66774.733333,6115.600000,-59275.000000,10616.666667,-187042.166667,226058.833333,-101433.333333
43,16,8,2017,204225.000000,-5.000000e-01,-8.660254e-01,44,176720.000000,177540.000000,218375.000000,...,-820.000000,-40835.000000,31891.666667,-45432.000000,66774.733333,6115.600000,-59275.000000,10616.666667,-187042.166667,226058.833333
44,16,9,2017,186425.000000,-8.660254e-01,-5.000000e-01,45,204225.000000,176720.000000,177540.000000,...,27505.000000,-820.000000,-40835.000000,31891.666667,-45432.000000,66774.733333,6115.600000,-59275.000000,10616.666667,-187042.166667
45,16,10,2017,184199.952000,-1.000000e+00,-1.836970e-16,46,186425.000000,204225.000000,176720.000000,...,-17800.000000,27505.000000,-820.000000,-40835.000000,31891.666667,-45432.000000,66774.733333,6115.600000,-59275.000000,10616.666667
46,16,11,2017,183100.000000,-8.660254e-01,5.000000e-01,47,184199.952000,186425.000000,204225.000000,...,-2225.048000,-17800.000000,27505.000000,-820.000000,-40835.000000,31891.666667,-45432.000000,66774.733333,6115.600000,-59275.000000
47,16,12,2017,191970.000000,-5.000000e-01,8.660254e-01,48,183100.000000,184199.952000,186425.000000,...,-1099.952000,-2225.048000,-17800.000000,27505.000000,-820.000000,-40835.000000,31891.666667,-45432.000000,66774.733333,6115.600000
60,26,1,2015,0.000000,0.000000e+00,1.000000e+00,13,105500.000000,92500.000000,210000.000000,...,13000.000000,-117500.000000,19987.500000,-57987.500000,35225.000000,112775.000000,-95000.000000,-52550.000000,51883.333333,64416.666667
61,26,2,2015,167000.000000,5.000000e-01,8.660254e-01,14,0.000000,105500.000000,92500.000000,...,-105500.000000,13000.000000,-117500.000000,19987.500000,-57987.500000,35225.000000,112775.000000,-95000.000000,-52550.000000,51883.333333
62,26,3,2015,831280.000000,8.660254e-01,5.000000e-01,15,167000.000000,0.000000,105500.000000,...,167000.000000,-105500.000000,13000.000000,-117500.000000,19987.500000,-57987.500000,35225.000000,112775.000000,-95000.000000,-52550.000000
63,26,4,2015,115000.000000,1.000000e+00,6.123234e-17,16,831280.000000,167000.000000,0.000000,...,664280.000000,167000.000000,-105500.000000,13000.000000,-117500.000000,19987.500000,-57987.500000,35225.000000,112775.000000,-95000.000000
64,26,5,2015,185000.000000,8.660254e-01,-5.000000e-01,17,115000.000000,831280.000000,167000.000000,...,-716280.000000,664280.000000,167000.000000,-105500.000000,13000.000000,-117500.000000,19987.500000,-57987.500000,35225.000000,112775.000000
65,26,6,2015,105500.000000,5.000000e-01,-8.660254e-01,18,185000.000000,115000.000000,831280.000000,...,70000.000000,-716280.000000,664280.000000,167000.000000,-105500.000000,13000.000000,-117500.000000,19987.500000,-57987.500000,35225.000000
66,26,7,2015,122050.000000,1.224647e-16,-1.000000e+00,19,105500.000000,185000.000000,115000.000000,...,-79500.000000,70000.000000,-716280.000000,664280.000000,167000.000000,-105500.000000,13000.000000,-117500.000000,19987.500000,-57987.500000
67,26,8,2015,155000.000000,-5.000000e-01,-8.660254e-01,20,122050.000000,105500.000000,185000.000000,...,16550.000000,-79500.000000,70000.000000,-716280.000000,664280.000000,167000.000000,-105500.000000,13000.000000,-117500.000000,19987.500000
68,26,9,2015,174666.666667,-8.660254e-01,-5.000000e-01,21,155000.000000,122050.000000,105500.000000,...,32950.000000,16550.000000,-79500.000000,70000.000000,-716280.000000,664280.000000,167000.000000,-105500.000000,13000.000000,-117500.000000
69,26,10,2015,156000.000000,-1.000000e+00,-1.836970e-16,22,174666.666667,155000.000000,122050.000000,...,19666.666667,32950.000000,16550.000000,-79500.000000,70000.000000,-716280.000000,664280.000000,167000.000000,-105500.000000,13000.000000
70,26,11,2015,128000.000000,-8.660254e-01,5.000000e-01,23,156000.000000,174666.666667,155000.000000,...,-18666.666667,19666.666667,32950.000000,16550.000000,-79500.000000,70000.000000,-716280.000000,664280.000000,167000.000000,-105500.000000
71,26,12,2015,174261.875000,-5.000000e-01,8.660254e-01,24,128000.000000,156000.000000,174666.666667,...,-28000.000000,-18666.666667,19666.666667,32950.000000,16550.000000,-79500.000000,70000.000000,-716280.000000,664280.000000,167000.000000
72,26,1,2016,134460.000000,0.000000e+00,1.000000e+00,25,174261.875000,128000.000000,156000.000000,...,46261.875000,-28000.000000,-18666.666667,19666.666667,32950.000000,16550.000000,-79500.000000,70000.000000,-716280.000000,664280.000000
73,26,2,2016,320000.000000,5.000000e-01,8.660254e-01,26,134460.000000,174261.875000,128000.000000,...,-39801.875000,46261.875000,-28000.000000,-18666.666667,19666.666667,32950.000000,16550.000000,-79500.000000,70000.000000,-716280.000000