In [1]:
import pandas as pd

### Import des pop ens

In [40]:
years = ["2014","2015"]

In [41]:
data_pop = {}
for year in years:
    pop = pd.read_csv('../../data/csp/ensemble_pop_'+ year + '.csv',sep=',',dtype= {'code_commune' : str})
    # pop.rename(columns = {'population_totale' : 'pop_' + year},inplace=True)
    data_pop[year] = pop

### Import de immo by year

In [42]:
immo = pd.read_csv('../../data/join/immo_by_year.csv',sep=',',dtype= {'code_commune' : str})

In [46]:
immo.head()

,id_bien,code_commune,nom_commune,type_local,code_type_local,nombre_pieces_principales,nb_mutation_2014,nb_mutation_2015,nb_mutation_2016,surface_2014,surface_2015,surface_2016,valeur_2014,valeur_2015,valeur_2016
0,01001_1_3,01001,L'Abergement-Clémenciat,Maison,1.0,3.0,1.0,1.0,1.0,62.000000,75.00,75.0,134750.000000,140000.0000,189000.0
1,01001_1_4,01001,L'Abergement-Clémenciat,Maison,1.0,4.0,3.0,2.0,2.0,100.000000,94.00,121.5,110666.666667,198000.0000,206000.0
2,01001_1_5,01001,L'Abergement-Clémenciat,Maison,1.0,5.0,2.0,4.0,0.0,102.000000,99.75,0.0,211500.000000,185500.3325,0.0
3,01001_1_6,01001,L'Abergement-Clémenciat,Maison,1.0,6.0,3.0,1.0,1.0,119.333333,157.00,123.0,213273.333333,149000.0000,217050.0
4,01001_1_7,01001,L'Abergement-Clémenciat,Maison,1.0,7.0,1.0,0.0,2.0,150.000000,0.00,206.5,272500.000000,0.0000,307475.0

In [47]:
immo.shape

(208674, 15)

### Join

In [48]:
immo_pop.shape

(208660, 159)

In [49]:
immo_pop = immo
for year in years:
    immo_pop = pd.merge(immo_pop, data_pop[year], on='code_commune', how='inner')

In [50]:
immo_pop.head()

,id_bien,code_commune,nom_commune,type_local,code_type_local,nombre_pieces_principales,nb_mutation_2014,nb_mutation_2015,nb_mutation_2016,surface_2014,...,c15_f15p_cs4,c15_f15p_cs5,c15_f15p_cs6,c15_f15p_cs7,c15_f15p_cs8,p15_pop_fr,p15_pop_etr,p15_pop_imm,p15_pmen,p15_phormen
0,01001_1_3,01001,L'Abergement-Clémenciat,Maison,1.0,3.0,1.0,1.0,1.0,62.000000,...,50.0,85.0,30.0,70.0,15.0,759.0,8.0,20.0,767.0,0.0
1,01001_1_4,01001,L'Abergement-Clémenciat,Maison,1.0,4.0,3.0,2.0,2.0,100.000000,...,50.0,85.0,30.0,70.0,15.0,759.0,8.0,20.0,767.0,0.0
2,01001_1_5,01001,L'Abergement-Clémenciat,Maison,1.0,5.0,2.0,4.0,0.0,102.000000,...,50.0,85.0,30.0,70.0,15.0,759.0,8.0,20.0,767.0,0.0
3,01001_1_6,01001,L'Abergement-Clémenciat,Maison,1.0,6.0,3.0,1.0,1.0,119.333333,...,50.0,85.0,30.0,70.0,15.0,759.0,8.0,20.0,767.0,0.0
4,01001_1_7,01001,L'Abergement-Clémenciat,Maison,1.0,7.0,1.0,0.0,2.0,150.000000,...,50.0,85.0,30.0,70.0,15.0,759.0,8.0,20.0,767.0,0.0

In [52]:
immo_pop.to_csv('../../data/join/join_immo_pop_ens.csv',index=False)