In [80]:
import pandas as pd
import numpy as np

In [81]:
immo = pd.read_csv('../../data/join/immo_by_month_100.csv',sep=',',dtype= {'code_commune' : str}).rename(columns = {'id_bien_int':'id_bien'})

In [82]:
immo.shape

(228000, 3)

In [83]:
immo.head()

   id_bien        valeur  mois
0       11  57166.666667     1
1       11  56500.000000     2
2       11  70750.000000     3
3       11  71013.333333     4
4       11  30500.000000     5

### Feature enginneering - ajout des variables observées à  t-i  ( lagk) avec i  dans [[1;k]]

In [84]:
cols_to_extract = ['valeur']

In [85]:
immo2 = immo.copy()
immo2 = immo2.sort_values(['mois','id_bien'])

In [86]:
k = 12

In [87]:
for i in range(1,k+1):
    lag1 = list(map(lambda x: x + "-"+str(i),cols_to_extract))
    immo2[lag1] = immo2.groupby(['id_bien'])[cols_to_extract].shift(i)

In [88]:
immo2.sort_values(by=['id_bien','mois']).head(20)

,id_bien,valeur,mois,valeur-1,valeur-2,valeur-3,valeur-4,valeur-5,valeur-6,valeur-7,valeur-8,valeur-9,valeur-10,valeur-11,valeur-12
0,11,57166.666667,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11,56500.000000,2,57166.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,70750.000000,3,56500.000000,57166.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,71013.333333,4,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,30500.000000,5,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,11,67333.333333,6,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,11,53675.000000,7,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,NaN,NaN,NaN
7,11,104000.000000,8,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,NaN,NaN
8,11,0.000000,9,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,NaN
9,11,52500.000000,10,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN
10,11,0.000000,11,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN
11,11,70000.000000,12,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN
12,11,45500.000000,13,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667
13,11,50485.000000,14,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000
14,11,55000.000000,15,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000
15,11,53000.000000,16,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333
16,11,55000.000000,17,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000
17,11,49000.000000,18,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333
18,11,56144.016667,19,49000.000000,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000
19,11,40526.666667,20,56144.016667,49000.000000,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000

### Feature enginneering - ajout des différences entre t-i et t-(i+1) (diffi) pour i dans [[1;k]]

In [89]:
k=10
for i in range(1,k+1):
    lag1 = list(map(lambda x: x + "-"+str(i),cols_to_extract))
    diff1 = list(map(lambda x: x + "_diff-"+str(i)+"-"+str(i+1),cols_to_extract))
    immo2[diff1] = immo2.groupby(['id_bien'])[lag1].diff()

In [90]:
immo2.sort_values(by=['id_bien','mois']).head(20)

,id_bien,valeur,mois,valeur-1,valeur-2,valeur-3,valeur-4,valeur-5,valeur-6,valeur-7,...,valeur_diff-1-2,valeur_diff-2-3,valeur_diff-3-4,valeur_diff-4-5,valeur_diff-5-6,valeur_diff-6-7,valeur_diff-7-8,valeur_diff-8-9,valeur_diff-9-10,valeur_diff-10-11
0,11,57166.666667,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11,56500.000000,2,57166.666667,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,70750.000000,3,56500.000000,57166.666667,NaN,NaN,NaN,NaN,NaN,...,-666.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,71013.333333,4,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,NaN,...,14250.000000,-666.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,30500.000000,5,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,NaN,...,263.333333,14250.000000,-666.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,11,67333.333333,6,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,NaN,...,-40513.333333,263.333333,14250.000000,-666.666667,NaN,NaN,NaN,NaN,NaN,NaN
6,11,53675.000000,7,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,NaN,...,36833.333333,-40513.333333,263.333333,14250.000000,-666.666667,NaN,NaN,NaN,NaN,NaN
7,11,104000.000000,8,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,57166.666667,...,-13658.333333,36833.333333,-40513.333333,263.333333,14250.000000,-666.666667,NaN,NaN,NaN,NaN
8,11,0.000000,9,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,56500.000000,...,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333,14250.000000,-666.666667,NaN,NaN,NaN
9,11,52500.000000,10,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,70750.000000,...,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333,14250.000000,-666.666667,NaN,NaN
10,11,0.000000,11,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,71013.333333,...,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333,14250.000000,-666.666667,NaN
11,11,70000.000000,12,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,30500.000000,...,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333,14250.000000,-666.666667
12,11,45500.000000,13,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,...,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333,14250.000000
13,11,50485.000000,14,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,...,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333
14,11,55000.000000,15,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,...,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333
15,11,53000.000000,16,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,...,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333
16,11,55000.000000,17,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,...,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333
17,11,49000.000000,18,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,...,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000
18,11,56144.016667,19,49000.000000,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,...,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000
19,11,40526.666667,20,56144.016667,49000.000000,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,...,7144.016667,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000

In [91]:
immo2.shape

(228000, 25)

In [92]:
immo_train = immo2.dropna()

In [93]:
immo_train.shape

(171000, 25)

### Export

In [94]:
immo_train.to_csv('../../data/ml/train_immo_100_more_k_12_10.csv',index=False)

In [95]:
immo_train.sort_values(by=['id_bien','mois']).head(50)

,id_bien,valeur,mois,valeur-1,valeur-2,valeur-3,valeur-4,valeur-5,valeur-6,valeur-7,...,valeur_diff-1-2,valeur_diff-2-3,valeur_diff-3-4,valeur_diff-4-5,valeur_diff-5-6,valeur_diff-6-7,valeur_diff-7-8,valeur_diff-8-9,valeur_diff-9-10,valeur_diff-10-11
12,11,45500.000000,13,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,67333.333333,...,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333,14250.000000
13,11,50485.000000,14,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,53675.000000,...,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333,263.333333
14,11,55000.000000,15,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,104000.000000,...,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333,-40513.333333
15,11,53000.000000,16,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,0.000000,...,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333,36833.333333
16,11,55000.000000,17,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,52500.000000,...,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000,-13658.333333
17,11,49000.000000,18,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,0.000000,...,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000,50325.000000
18,11,56144.016667,19,49000.000000,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,70000.000000,...,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000,-104000.000000
19,11,40526.666667,20,56144.016667,49000.000000,55000.000000,53000.000000,55000.000000,50485.000000,45500.000000,...,7144.016667,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000,52500.000000
20,11,50130.000000,21,40526.666667,56144.016667,49000.000000,55000.000000,53000.000000,55000.000000,50485.000000,...,-15617.350000,7144.016667,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000,-52500.000000
21,11,93336.666667,22,50130.000000,40526.666667,56144.016667,49000.000000,55000.000000,53000.000000,55000.000000,...,9603.333333,-15617.350000,7144.016667,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000,70000.000000
22,11,53375.000000,23,93336.666667,50130.000000,40526.666667,56144.016667,49000.000000,55000.000000,53000.000000,...,43206.666667,9603.333333,-15617.350000,7144.016667,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000,-24500.000000
23,11,57260.000000,24,53375.000000,93336.666667,50130.000000,40526.666667,56144.016667,49000.000000,55000.000000,...,-39961.666667,43206.666667,9603.333333,-15617.350000,7144.016667,-6000.000000,2000.000000,-2000.000000,4515.000000,4985.000000
24,11,39600.000000,25,57260.000000,53375.000000,93336.666667,50130.000000,40526.666667,56144.016667,49000.000000,...,3885.000000,-39961.666667,43206.666667,9603.333333,-15617.350000,7144.016667,-6000.000000,2000.000000,-2000.000000,4515.000000
25,11,63312.000000,26,39600.000000,57260.000000,53375.000000,93336.666667,50130.000000,40526.666667,56144.016667,...,-17660.000000,3885.000000,-39961.666667,43206.666667,9603.333333,-15617.350000,7144.016667,-6000.000000,2000.000000,-2000.000000
26,11,49650.000000,27,63312.000000,39600.000000,57260.000000,53375.000000,93336.666667,50130.000000,40526.666667,...,23712.000000,-17660.000000,3885.000000,-39961.666667,43206.666667,9603.333333,-15617.350000,7144.016667,-6000.000000,2000.000000
27,11,61000.000000,28,49650.000000,63312.000000,39600.000000,57260.000000,53375.000000,93336.666667,50130.000000,...,-13662.000000,23712.000000,-17660.000000,3885.000000,-39961.666667,43206.666667,9603.333333,-15617.350000,7144.016667,-6000.000000
28,11,72500.000000,29,61000.000000,49650.000000,63312.000000,39600.000000,57260.000000,53375.000000,93336.666667,...,11350.000000,-13662.000000,23712.000000,-17660.000000,3885.000000,-39961.666667,43206.666667,9603.333333,-15617.350000,7144.016667
29,11,53038.000000,30,72500.000000,61000.000000,49650.000000,63312.000000,39600.000000,57260.000000,53375.000000,...,11500.000000,11350.000000,-13662.000000,23712.000000,-17660.000000,3885.000000,-39961.666667,43206.666667,9603.333333,-15617.350000
30,11,60075.000000,31,53038.000000,72500.000000,61000.000000,49650.000000,63312.000000,39600.000000,57260.000000,...,-19462.000000,11500.000000,11350.000000,-13662.000000,23712.000000,-17660.000000,3885.000000,-39961.666667,43206.666667,9603.333333
31,11,53000.000000,32,60075.000000,53038.000000,72500.000000,61000.000000,49650.000000,63312.000000,39600.000000,...,7037.000000,-19462.000000,11500.000000,11350.000000,-13662.000000,23712.000000,-17660.000000,3885.000000,-39961.666667,43206.666667
32,11,57818.666667,33,53000.000000,60075.000000,53038.000000,72500.000000,61000.000000,49650.000000,63312.000000,...,-7075.000000,7037.000000,-19462.000000,11500.000000,11350.000000,-13662.000000,23712.000000,-17660.000000,3885.000000,-39961.666667
33,11,46000.000000,34,57818.666667,53000.000000,60075.000000,53038.000000,72500.000000,61000.000000,49650.000000,...,4818.666667,-7075.000000,7037.000000,-19462.000000,11500.000000,11350.000000,-13662.000000,23712.000000,-17660.000000,3885.000000
34,11,56650.000000,35,46000.000000,57818.666667,53000.000000,60075.000000,53038.000000,72500.000000,61000.000000,...,-11818.666667,4818.666667,-7075.000000,7037.000000,-19462.000000,11500.000000,11350.000000,-13662.000000,23712.000000,-17660.000000
35,11,53218.750000,36,56650.000000,46000.000000,57818.666667,53000.000000,60075.000000,53038.000000,72500.000000,...,10650.000000,-11818.666667,4818.666667,-7075.000000,7037.000000,-19462.000000,11500.000000,11350.000000,-13662.000000,23712.000000
36,11,51487.500000,37,53218.750000,56650.000000,46000.000000,57818.666667,53000.000000,60075.000000,53038.000000,...,-3431.250000,10650.000000,-11818.666667,4818.666667,-7075.000000,7037.000000,-19462.000000,11500.000000,11350.000000,-13662.000000
37,11,57766.666667,38,51487.500000,53218.750000,56650.000000,46000.000000,57818.666667,53000.000000,60075.000000,...,-1731.250000,-3431.250000,10650.000000,-11818.666667,4818.666667,-7075.000000,7037.000000,-19462.000000,11500.000000,11350.000000
38,11,65675.000000,39,57766.666667,51487.500000,53218.750000,56650.000000,46000.000000,57818.666667,53000.000000,...,6279.166667,-1731.250000,-3431.250000,10650.000000,-11818.666667,4818.666667,-7075.000000,7037.000000,-19462.000000,11500.000000
39,11,57060.000000,40,65675.000000,57766.666667,51487.500000,53218.750000,56650.000000,46000.000000,57818.666667,...,7908.333333,6279.166667,-1731.250000,-3431.250000,10650.000000,-11818.666667,4818.666667,-7075.000000,7037.000000,-19462.000000
40,11,25375.000000,41,57060.000000,65675.000000,57766.666667,51487.500000,53218.750000,56650.000000,46000.000000,...,-8615.000000,7908.333333,6279.166667,-1731.250000,-3431.250000,10650.000000,-11818.666667,4818.666667,-7075.000000,7037.000000
41,11,46211.428571,42,25375.000000,57060.000000,65675.000000,57766.666667,51487.500000,53218.750000,56650.000000,...,-31685.000000,-8615.000000,7908.333333,6279.166667,-1731.250000,-3431.250000,10650.000000,-11818.666667,4818.666667,-7075.000000
42,11,69700.000000,43,46211.428571,25375.000000,57060.000000,65675.000000,57766.666667,51487.500000,53218.750000,...,20836.428571,-31685.000000,-8615.000000,7908.333333,6279.166667,-1731.250000,-3431.250000,10650.000000,-11818.666667,4818.666667
43,11,55891.666667,44,69700.000000,46211.428571,25375.000000,57060.000000,65675.000000,57766.666667,51487.500000,...,23488.571429,20836.428571,-31685.000000,-8615.000000,7908.333333,6279.166667,-1731.250000,-3431.250000,10650.000000,-11818.666667
44,11,70608.333333,45,55891.666667,69700.000000,46211.428571,25375.000000,57060.000000,65675.000000,57766.666667,...,-13808.333333,23488.571429,20836.428571,-31685.000000,-8615.000000,7908.333333,6279.166667,-1731.250000,-3431.250000,10650.000000
45,11,71000.000000,46,70608.333333,55891.666667,69700.000000,46211.428571,25375.000000,57060.000000,65675.000000,...,14716.666667,-13808.333333,23488.571429,20836.428571,-31685.000000,-8615.000000,7908.333333,6279.166667,-1731.250000,-3431.250000
46,11,65000.000000,47,71000.000000,70608.333333,55891.666667,69700.000000,46211.428571,25375.000000,57060.000000,...,391.666667,14716.666667,-13808.333333,23488.571429,20836.428571,-31685.000000,-8615.000000,7908.333333,6279.166667,-1731.250000
47,11,43100.000000,48,65000.000000,71000.000000,70608.333333,55891.666667,69700.000000,46211.428571,25375.000000,...,-6000.000000,391.666667,14716.666667,-13808.333333,23488.571429,20836.428571,-31685.000000,-8615.000000,7908.333333,6279.166667
60,23,547500.000000,13,229966.666667,689000.000000,393300.333333,231677.333333,267866.666667,412393.333333,487236.000000,...,-459033.333333,295699.666667,161623.000000,-36189.333333,-144526.666667,-74842.666667,-77764.000000,-151900.000000,321900.000000,175143.966667
61,23,217000.000000,14,547500.000000,229966.666667,689000.000000,393300.333333,231677.333333,267866.666667,412393.333333,...,317533.333333,-459033.333333,295699.666667,161623.000000,-36189.333333,-144526.666667,-74842.666667,-77764.000000,-151900.000000,321900.000000
62,23,272273.000000,15,217000.000000,547500.000000,229966.666667,689000.000000,393300.333333,231677.333333,267866.666667,...,-330500.000000,317533.333333,-459033.333333,295699.666667,161623.000000,-36189.333333,-144526.666667,-74842.666667,-77764.000000,-151900.000000
63,23,219250.000000,16,272273.000000,217000.000000,547500.000000,229966.666667,689000.000000,393300.333333,231677.333333,...,55273.000000,-330500.000000,317533.333333,-459033.333333,295699.666667,161623.000000,-36189.333333,-144526.666667,-74842.666667,-77764.000000
64,23,637000.000000,17,219250.000000,272273.000000,217000.000000,547500.000000,229966.666667,689000.000000,393300.333333,...,-53023.000000,55273.000000,-330500.000000,317533.333333,-459033.333333,295699.666667,161623.000000,-36189.333333,-144526.666667,-74842.666667
65,23,646905.000000,18,637000.000000,219250.000000,272273.000000,217000.000000,547500.000000,229966.666667,689000.000000,...,417750.000000,-53023.000000,55273.000000,-330500.000000,317533.333333,-459033.333333,295699.666667,161623.000000,-36189.333333,-144526.666667
66,23,415384.285714,19,646905.000000,637000.000000,219250.000000,272273.000000,217000.000000,547500.000000,229966.666667,...,9905.000000,417750.000000,-53023.000000,55273.000000,-330500.000000,317533.333333,-459033.333333,295699.666667,161623.000000,-36189.333333
67,23,257600.000000,20,415384.285714,646905.000000,637000.000000,219250.000000,272273.000000,217000.000000,547500.000000,...,-231520.714286,9905.000000,417750.000000,-53023.000000,55273.000000,-330500.000000,317533.333333,-459033.333333,295699.666667,161623.000000
68,23,468280.000000,21,257600.000000,415384.285714,646905.000000,637000.000000,219250.000000,272273.000000,217000.000000,...,-157784.285714,-231520.714286,9905.000000,417750.000000,-53023.000000,55273.000000,-330500.000000,317533.333333,-459033.333333,295699.666667
69,23,405350.000000,22,468280.000000,257600.000000,415384.285714,646905.000000,637000.000000,219250.000000,272273.000000,...,210680.000000,-157784.285714,-231520.714286,9905.000000,417750.000000,-53023.000000,55273.000000,-330500.000000,317533.333333,-459033.333333
70,23,292450.000000,23,405350.000000,468280.000000,257600.000000,415384.285714,646905.000000,637000.000000,219250.000000,...,-62930.000000,210680.000000,-157784.285714,-231520.714286,9905.000000,417750.000000,-53023.000000,55273.000000,-330500.000000,317533.333333
71,23,732356.666667,24,292450.000000,405350.000000,468280.000000,257600.000000,415384.285714,646905.000000,637000.000000,...,-112900.000000,-62930.000000,210680.000000,-157784.285714,-231520.714286,9905.000000,417750.000000,-53023.000000,55273.000000,-330500.000000
72,23,461450.000000,25,732356.666667,292450.000000,405350.000000,468280.000000,257600.000000,415384.285714,646905.000000,...,439906.666667,-112900.000000,-62930.000000,210680.000000,-157784.285714,-231520.714286,9905.000000,417750.000000,-53023.000000,55273.000000
73,23,313500.000000,26,461450.000000,732356.666667,292450.000000,405350.000000,468280.000000,257600.000000,415384.285714,...,-270906.666667,439906.666667,-112900.000000,-62930.000000,210680.000000,-157784.285714,-231520.714286,9905.000000,417750.000000,-53023.000000